name: CI/CD Pipeline

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: compile with maven
        run: mvn compile
      - name: Run tests
        run: mvn test
      - name: Coverage with JaCoCo
        if: always()
        run: mvn jacoco:report
      - name: Publish coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: fma-coverage
          path: ./target/site/jacoco